#!/usr/bin/env bash
#
# validate-jamesdsp.sh — sanity-check the jamesdsp/ export bundle.
#
# jamesdsp/ is generated by:
#   scripts/generate-jamesdsp-convolver.js  -> jamesdsp/Convolver/*.irs (copied verbatim from irs/)
#   scripts/convert-sofa-to-jamesdsp.py     -> jamesdsp/Convolver/*.wav (SOFA presets flattened to
#                                              fixed +-30 deg true-stereo, since JamesDSP has no
#                                              SOFA/HDF5 support)
#   scripts/generate-jamesdsp-eq.js         -> jamesdsp/ParametricEQ/*.txt (EqualizerAPO export of
#                                              every preset's equalizer#0 block, for JamesDSP's
#                                              Parametric EQ importer)
#
# What this checks:
#   1. jamesdsp/Convolver/ has exactly one file per non-.sofa file in irs/ (same filename).
#   2. Each of the two SOFA presets has a corresponding converted true-stereo .wav in
#      jamesdsp/Convolver/.
#   3. jamesdsp/ParametricEQ/ has exactly one <preset>.txt per root *.json preset that has an
#      "equalizer#0" block, no more, no less.
#   4. Every jamesdsp/ParametricEQ/*.txt starts with a "Preamp: <num> dB" line and every
#      subsequent non-blank line matches JamesDSP's own EqualizerAPO import regex:
#        Filter <n>: ON <PK|LSC|HSC> Fc <freq> Hz Gain <gain> dB Q <q>
#      with strictly sequential Filter numbering starting at 1.
#
# Usage:
#   ./scripts/validate-jamesdsp.sh
# Run from anywhere; the script cd's to the repo root on its own. Exit status is non-zero if any
# check fails. Requires python3 (used the same way validate-presets.sh does, stdlib json only).

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT" || { echo "error: cannot cd to repo root" >&2; exit 2; }

if ! command -v python3 >/dev/null 2>&1; then
    echo "error: python3 is required (stdlib json module) but was not found in PATH" >&2
    exit 2
fi

fail_count=0
warn_count=0

fail() { echo "[FAIL] $1"; fail_count=$((fail_count + 1)); }
warn() { echo "[WARN] $1"; warn_count=$((warn_count + 1)); }
pass() { echo "[PASS] $1"; }

if [ ! -d jamesdsp/Convolver ]; then
    fail "jamesdsp/Convolver/ does not exist (run scripts/generate-jamesdsp-convolver.js and scripts/convert-sofa-to-jamesdsp.py first)"
fi
if [ ! -d jamesdsp/ParametricEQ ]; then
    fail "jamesdsp/ParametricEQ/ does not exist (run scripts/generate-jamesdsp-eq.js first)"
fi

# --- 1 & 2: Convolver bundle completeness -----------------------------------------------------
if [ -d irs ] && [ -d jamesdsp/Convolver ]; then
    shopt -s nullglob
    irs_files=( irs/*.irs )
    sofa_files=( irs/*.sofa )
    shopt -u nullglob

    missing=0
    for f in "${irs_files[@]}"; do
        name="$(basename "$f")"
        if [ ! -f "jamesdsp/Convolver/$name" ]; then
            fail "jamesdsp/Convolver/$name missing (source: $f)"
            missing=$((missing + 1))
        fi
    done
    if [ "$missing" -eq 0 ] && [ "${#irs_files[@]}" -gt 0 ]; then
        pass "all ${#irs_files[@]} plain irs/*.irs kernels present in jamesdsp/Convolver/"
    fi

    extra_sofa=$(find jamesdsp/Convolver -maxdepth 1 -iname '*.sofa' 2>/dev/null | wc -l | tr -d ' ')
    if [ "$extra_sofa" -ne 0 ]; then
        fail "jamesdsp/Convolver/ contains $extra_sofa .sofa file(s) — JamesDSP cannot load SOFA, these must be converted to .wav"
    fi

    for f in "${sofa_files[@]}"; do
        base="$(basename "$f" .sofa)"
        match=$(find jamesdsp/Convolver -maxdepth 1 -iname "${base%.sofa}*.wav" 2>/dev/null | head -1)
        if [ -z "$match" ]; then
            # fall back to a looser match since converted files are renamed (e.g. drop "(Normal Pinna)")
            found=0
            for w in jamesdsp/Convolver/*.wav; do
                [ -e "$w" ] || continue
                case "$(basename "$w")" in
                    *"$(echo "$base" | cut -d'(' -f1 | sed 's/[[:space:]]*$//')"*) found=1 ;;
                esac
            done
            if [ "$found" -eq 0 ]; then
                fail "no converted true-stereo .wav found in jamesdsp/Convolver/ for SOFA source $f"
            else
                pass "converted .wav found for SOFA source $f"
            fi
        else
            pass "converted .wav found for SOFA source $f -> $(basename "$match")"
        fi
    done
fi

# --- 3 & 4: ParametricEQ bundle completeness + format ------------------------------------------
if [ -d jamesdsp/ParametricEQ ]; then
    expected_presets="$(python3 - <<'PYEOF'
import json, glob, os
for f in sorted(glob.glob("*.json")):
    try:
        data = json.load(open(f, encoding="utf-8"))
    except Exception:
        continue
    out = data.get("output", {})
    if any(k.startswith("equalizer#") for k in out.keys()):
        print(os.path.splitext(f)[0])
PYEOF
)"

    expected_count=0
    missing_eq=0
    while IFS= read -r preset; do
        [ -z "$preset" ] && continue
        expected_count=$((expected_count + 1))
        if [ ! -f "jamesdsp/ParametricEQ/$preset.txt" ]; then
            fail "jamesdsp/ParametricEQ/$preset.txt missing (preset has an equalizer#0 block)"
            missing_eq=$((missing_eq + 1))
        fi
    done <<< "$expected_presets"

    shopt -s nullglob
    actual_files=( jamesdsp/ParametricEQ/*.txt )
    shopt -u nullglob
    actual_count="${#actual_files[@]}"

    if [ "$missing_eq" -eq 0 ] && [ "$expected_count" -gt 0 ]; then
        pass "all $expected_count equalizer-bearing presets have a jamesdsp/ParametricEQ/*.txt export"
    fi
    if [ "$actual_count" -ne "$expected_count" ]; then
        warn "jamesdsp/ParametricEQ/ has $actual_count file(s) but $expected_count preset(s) have an equalizer#0 block (extra/stale export file?)"
    fi

    for f in "${actual_files[@]}"; do
        name="$(basename "$f")"
        py_result=$(python3 - "$f" <<'PYEOF'
import re, sys
path = sys.argv[1]
lines = [l.rstrip("\n") for l in open(path, encoding="utf-8") if l.strip()]
if not lines or not re.match(r"^Preamp:\s*-?\d+(\.\d+)?\s*dB$", lines[0]):
    print("BAD_PREAMP")
    sys.exit()
filt_re = re.compile(r"^Filter\s+(\d+):\s+ON\s+(PK|LSC|HSC)\s+Fc\s+([\d.]+)\s+Hz\s+Gain\s+(-?[\d.]+)\s+dB\s+Q\s+([\d.]+)$")
expected_n = 1
for line in lines[1:]:
    m = filt_re.match(line)
    if not m:
        print(f"BAD_FILTER_LINE:{line}")
        sys.exit()
    n = int(m.group(1))
    if n != expected_n:
        print(f"OUT_OF_ORDER:{line}")
        sys.exit()
    expected_n += 1
print(f"OK:{expected_n - 1}")
PYEOF
)
        case "$py_result" in
            OK:*) pass "$name: well-formed (${py_result#OK:} band(s), sequential Filter numbering)" ;;
            BAD_PREAMP) fail "$name: missing/malformed 'Preamp: <n> dB' first line" ;;
            BAD_FILTER_LINE:*) fail "$name: line does not match JamesDSP's Filter regex: ${py_result#BAD_FILTER_LINE:}" ;;
            OUT_OF_ORDER:*) fail "$name: Filter numbering not sequential at: ${py_result#OUT_OF_ORDER:}" ;;
            *) fail "$name: unexpected validator result: $py_result" ;;
        esac
    done
fi

echo
echo "Summary: $fail_count failure(s), $warn_count warning(s)"

if [ "$fail_count" -gt 0 ]; then
    exit 1
fi
exit 0
